### ISSUE TITLE
Game crashes when going to a custom level, opening the icon kit, closing it, and pressing the play button.

### ISSUE THREAD

**Issue by legowiifun** [RayDeeUx/BreakingPlatforming#2]
Doing these actions in this order crashes the game and gives the attached crashlog. I have identified that disabling this mod prevents the crash. 
[2024-04-10_16-22-56.log](https://github.com/RayDeeUx/BreakingPlatforming/files/14940590/2024-04-10_16-22-56.log)

**Comment by RayDeeUx** [comment]
seems to be a crash from geode's notifications system.

there's no easy way to fix this without some moving and shaking from their end; i've made a toggle to prevent opening the garage (off by default so i don't get yelled at by the lead devs). check v1.1.1 in about 14 minutes from this reply being posted

**Comment by RayDeeUx** [comment]
never mind, give me another 15 hours, alk messed up the build.yml workflow file
